### ISSUE TITLE
Postgresql not getting connected with golang - Golang Microservices: Caching with Redis

### ISSUE THREAD

**Issue by najamsk** [MarioCarrion/videos#11]
Hello Mario,

I was trying to replicate your tutorial here and facing hard time running it. 

I am able to run following:
* postgresql running in docker with your command so localhost, user, password and db are same
* able to run migrate command so schema is there. 
* also able to connect to this instance and schema using table plus gui tool on mac
when i run following command 
`DATABASE_URL=postgres://user:password@localhost:5432/dbname?sslmode=disable REDIS=localhost:6379 go run .`

it throws following error 

```
2022/12/16 16:36:39 Could not initialize Database connection failed to connect to `host=/private/tmp user=najam database=`: dial error (dial unix /private/tmp/.s.PGSQL.5432: connect: no such file or directory)
exit status 1
```

Any idea what could be wrong

**Comment by najamsk** [comment]
? mark is creating problem so if you escape it by using \?

final command will be 

DATABASE_URL=postgres://user:password@localhost:5432/dbname\?sslmode=disable \
      REDIS=localhost:6379 \
        go run .

**Comment by MarioCarrion** [comment]
It looks like you figured it and fixed in https://github.com/MarioCarrion/videos/pull/12. So I'm closing the issue, thanks.
