### ISSUE TITLE
sqlc route is not using sqlc generated code 

### ISSUE THREAD

**Issue by najamsk** [MarioCarrion/videos#4]
https://github.com/MarioCarrion/videos/blob/50f2252b85d8fb1e8b41ae046c009d7e9fca8161/2021/02/09-go-database-postgresql-part-3/server.go#L162

**Comment by MarioCarrion** [comment]
Thanks @najamsk I'll work on fixing this.

**Comment by najamsk** [comment]
no worries good sir. I am glad its working now.
