### ISSUE TITLE
zsh and migrate command

### ISSUE THREAD

**Issue by najamsk** [MarioCarrion/videos#6]
migrate -path db/migrations/ -database postgres://user:password@localhost:5432/dbname?sslmode=disable up

above fails in wsl2 with zsh. after little googling it can be fixed by wrapping postgres connection string in double quotes

Following works:
migrate -path db/migrations/ -database "postgres://user:password@localhost:5432/dbname?sslmode=disable" up

dont know wrapping in double quotes works in mac too since I dont have access to a mac

**Comment by MarioCarrion** [comment]
Thanks @najamsk for opening the issue, using `"..."` works in Bash on Mac.

I updated all the `README.md` s that mention `migrate` to wrap the `-database` argument using double quotes.
